config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tasks
  resources :users

  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user

	def complete?
		!complete_at.blank?
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def complete
    @task.update_attribute(:completed_at, Time.now)
    direct_to @quest, notice: "Task Fulfilled"
  end


  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
        format.json { render :index, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path, notice: 'Task was successfully updated.' }
        format.json { render :index, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @task.destroy
      flash[:success] = "Task was abandoned"
    else
      flash[:error] = "Task could not be abandoned"
    end
    redirect_to @task
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :complete)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LifeUp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>

  <%= yield %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_partial.erb
<div class="row clearfix">
	<% if task.completed? %>
		<div class="complete">
			<%= link_to complete_task_path(task.id), method: :patch do %>
				<i style="opacity: 0.4;" class="fa fa-check"></i>
			<% end %>
		</div>
		<div class="todo_item">
			<p style="opacity: 0.4;"><strike><%= task.name %></strike></p>
		</div>
		<div class="trash">
			<%= link_to task_path(task.id), method: :delete, data: {confirm: "Are you sure you want to abandon the task?"} do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>

	<% else %>

		<div class="complete">
			<%= link_to complete_task_path(task.id), method: :patch do %>
				<i class="fa fa-check"></i>
			<% end %>
		</div>
		<div class="todo_item">
			<p><%= task.name %></p>
		</div>
		<div class="trash">
			<%= link_to task_path(@quest_log, quest.id), method: :delete, data: {confirm: "Are you sure you want to abandon the task?"} do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>
	<% end %>
</div>

app/views/tasks/_partial.html.erb
<div class="row clearfix">
	<% if @task.completed? %>
		<div class="complete">
			<%= link_to complete_task_path(@task, task.id), method: :patch do %>
				<i style="opacity: 0.4;" class="fa fa-check"></i>
			<% end %>
		</div>
		<div class="todo_item">
			<p style="opacity: 0.4;"><strike><%= task.name %></strike></p>
		</div>
		<div class="trash">
			<%= link_to task_path(@task, task.id), method: :delete, data: {confirm: "Are you sure you want to abandon the task?"} do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>

	<% else %>

		<div class="complete">
			<%= link_to complete_task_path(@task, task.id), method: :patch do %>
				<i class="fa fa-check"></i>
			<% end %>
		</div>
		<div class="todo_item">
			<p><%= task.name %></p>
		</div>
		<div class="trash">
			<%= link_to task_path(@task, task.id), method: :delete, data: {confirm: "Are you sure you want to abandon the task?"} do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>
	<% end %>
</div>

app/views/tasks/edit.html.erb
<h1 class="todo_list_title">Editing Task</h1>

<div class="forms">
	<%= render 'form' %>
</div>
<div class="links">
	<%= link_to 'Cancel', tasks_path %>
</div>
<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<% @tasks.each do |task|%>
  <div class="index_row clearfix">
    <h2 class="todo_list_wrapper">
      <%= task.name %>
      <div id="form">
        <%= render 'partial'%>
      </div>
    </h2>
  </div>
<% end %>
<div class="links">
  <%= link_to 'New Task', new_task_path %>
</div>

app/views/tasks/new.html.erb
<h1 class="todo_item_title">New Task</h1>

<div class ="form">
	<%= render 'form' %>
</div>
<div class="links">
	<%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<h2 class"todo_list_sub_title"><%= @task.name %></h2>

<div class="links">
	<%= link_to 'Edit', edit_task_path(@task) %> |
	<%= link_to 'Delete', task_path(@task), method: :delete, data: {confirm: "Are you sureyou want to delete this task?"}%>
	<%= link_to 'Back', tasks_path %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>